baseurl = "https://www.zeekhuge.me/"
pygmentsuseclasses = "true"
layoutdir = "layouts"
languageCode = "en-us"
title = "ZeekHuge"
theme = "HugoMDL"
disqusShortname = "zeekhuge"
disqus_identifier = "ZeekHuge"
MetaDataFormat = "yaml"
[permalinks]

	page = "/:title/"
	about = "/:filename/"

[params]
    author = "ZeekHuge"
    avatar = "https://avatars1.githubusercontent.com/u/8711218?v=3&s=460"
    background = "/images/back.jpg"
    description = "A place to publish my incomprehensible ramblings" #meta description
    image = "/images/av.jpg" #for frontpage profile card
    
    website = "www.zeekhuge.me"
    email = "zeekhuge@gmail.com"
    #twitter = "https://twitter.com/firstname_lastname"
    github = "https://github.com/ZeekHuge/"
    #linkedin = "https://linkedin.com/in/firstname_lastname/"
    facebook = "https://www.facebook.com/zubeen.tolani"
    copyrightyear = "2016"
    frontpageposts = 6 #number of post cards to display on frontpage
    
